services:
  app:
    image: app    # docker build -t netflix-app .
    container_name: netflix
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://autorack.proxy.rlwy.net:17450/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - springboot-mysql
    restart: on-failure

volumes:
  mysql-data:

networks:
  springboot-mysql:
    driver: bridge